<a href="https://colab.research.google.com/github/ekanshi258/eye-cluster-emotions/blob/master/cluster_features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np

from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [ ]:
df = pd.read_csv('features.csv')
df = df.drop(columns=['Unnamed: 0'])
df.head()

1.0       2.0       4.0       5.0       6.0      7.0  45.0  emotion
0  0.0  0.000000  1.008197  0.000000  0.221053  0.78481   3.0      7.0
1  0.6  0.545455  1.008197  1.130435  0.221053  0.78481   3.0      5.0
2  0.0  0.000000  1.008197  0.000000  0.221053  0.78481   3.0      7.0
3  0.6  0.545455  1.008197  1.130435  0.221053  2.00000   3.0      3.0
4  0.6  0.545455  1.008197  1.130435  0.000000  0.78481   3.0      5.0

In [ ]:
df.shape

(327, 8)

In [ ]:
fdf = df.drop(columns=['emotion'])
fdf.head()

1.0       2.0       4.0       5.0       6.0      7.0  45.0
0  0.0  0.000000  1.008197  0.000000  0.221053  0.78481   3.0
1  0.6  0.545455  1.008197  1.130435  0.221053  0.78481   3.0
2  0.0  0.000000  1.008197  0.000000  0.221053  0.78481   3.0
3  0.6  0.545455  1.008197  1.130435  0.221053  2.00000   3.0
4  0.6  0.545455  1.008197  1.130435  0.000000  0.78481   3.0

In [ ]:
tdf = fdf.T
tdf

0         1         2    ...       324       325       326
1.0   0.000000  0.600000  0.000000  ...  0.600000  4.000000  0.600000
2.0   0.000000  0.545455  0.000000  ...  0.545455  4.000000  0.545455
4.0   1.008197  1.008197  1.008197  ...  1.008197  1.008197  1.008197
5.0   0.000000  1.130435  0.000000  ...  1.130435  3.000000  1.130435
6.0   0.221053  0.221053  0.221053  ...  0.221053  0.221053  0.000000
7.0   0.784810  0.784810  0.784810  ...  0.784810  0.784810  0.784810
45.0  3.000000  3.000000  3.000000  ...  3.000000  3.000000  3.000000

[7 rows x 327 columns]

**CLUSTERING FEATURES: K-Means Clustering:**  
K-Means Clustering with K=2 and K=3

First, with K = 2:

In [ ]:
from sklearn.cluster import KMeans
# K=2
k2means = KMeans(n_clusters=2, random_state=42).fit(tdf)
k2means.labels_

array([0, 0, 0, 0, 0, 0, 1], dtype=int32)

In [ ]:
k2means.cluster_centers_

array([[0.33567658, 0.71499147, 0.33567658, 0.91752311, 0.67814936,
        0.33567658, 0.31615699, 0.54695868, 0.71499147, 0.71499147,
        1.11362535, 1.50234325, 0.67814936, 0.54695868, 0.41615699,
        0.88068101, 0.54734767, 0.44695868, 0.66900991, 0.41615699,
        0.67814936, 0.44695868, 0.33567658, 0.25855288, 1.25085645,
        1.11362535, 1.00234325, 0.71499147, 0.54734767, 0.66900991,
        0.54734767, 0.67814936, 0.52408238, 0.37931489, 2.16900991,
        1.37931489, 0.41615699, 0.41615699, 0.67814936, 0.67814936,
        0.74949033, 0.71499147, 0.33567658, 1.87931489, 1.18938292,
        1.35604959, 0.54734767, 0.25855288, 0.52658567, 0.71499147,
        0.33567658, 0.9483248 , 0.67814936, 0.71499147, 0.41615699,
        1.61362535, 0.33567658, 0.71499147, 1.0114827 , 0.67814936,
        0.37931489, 0.50234325, 1.04695868, 0.67814936, 0.33567658,
        0.71499147, 0.67814936, 0.50234325, 0.41615699, 0.37931489,
        0.67814936, 1.21362535, 0.33567658, 0.41

Clearly, the clustering is very skewed as 6 out of 7 features have been clustered into one, while only one feature constitutes the second cluster. However, We will still try to classify based on this. 

Saving the data from the features taken from above

In [ ]:
k2df = pd.DataFrame(data=k2means.cluster_centers_, index=['f1','f2'])
k2df = k2df.T
k2df

f1   f2
0    0.335677  3.0
1    0.714991  3.0
2    0.335677  3.0
3    0.917523  3.0
4    0.678149  3.0
..        ...  ...
322  0.416157  3.0
323  0.416157  3.0
324  0.714991  3.0
325  2.169010  3.0
326  0.678149  3.0

[327 rows x 2 columns]

In [ ]:
k2df = k2df.join(df['emotion'])     # Join the emotion labels
k2df

f1   f2  emotion
0    0.335677  3.0      7.0
1    0.714991  3.0      5.0
2    0.335677  3.0      7.0
3    0.917523  3.0      3.0
4    0.678149  3.0      5.0
..        ...  ...      ...
322  0.416157  3.0      1.0
323  0.416157  3.0      3.0
324  0.714991  3.0      3.0
325  2.169010  3.0      7.0
326  0.678149  3.0      5.0

[327 rows x 3 columns]

In [ ]:
k2df.to_csv('k2means_eye.csv')

Similarly, using k = 3:

In [ ]:
k3means = KMeans(n_clusters=3, random_state=42).fit(tdf)
k3means.labels_

array([2, 2, 0, 0, 2, 2, 1], dtype=int32)

In [ ]:
k3means.cluster_centers_

array([[0.50409836, 1.06931575, 0.50409836, 1.06931575, 1.06931575,
        0.50409836, 0.56521739, 0.56521739, 1.06931575, 1.06931575,
        1.56521739, 1.00409836, 1.06931575, 0.56521739, 0.56521739,
        1.06931575, 1.06931575, 0.56521739, 1.50409836, 0.56521739,
        1.06931575, 0.56521739, 0.50409836, 0.        , 1.06931575,
        1.56521739, 2.50409836, 1.06931575, 1.06931575, 1.50409836,
        1.06931575, 1.06931575, 1.06931575, 0.56521739, 2.00409836,
        1.56521739, 0.56521739, 0.56521739, 1.06931575, 1.06931575,
        0.56521739, 1.06931575, 0.50409836, 2.56521739, 1.06521739,
        1.56521739, 1.06931575, 0.        , 0.50409836, 1.06931575,
        0.50409836, 1.06931575, 1.06931575, 1.06931575, 0.56521739,
        3.06521739, 0.50409836, 1.06931575, 1.06931575, 1.06931575,
        0.56521739, 1.00409836, 2.06521739, 1.06931575, 0.50409836,
        1.06931575, 1.06931575, 1.00409836, 0.56521739, 0.56521739,
        1.06931575, 2.56521739, 0.50409836, 0.56

Again it is seen that AU45 is in it's own cluster, while the other features are divided into two clusters in a 1:2 ratio. We will save the data from this clustering as well.

In [ ]:
k3df = pd.DataFrame(data=k3means.cluster_centers_, index=['f1','f2', 'f3'])
k3df = k3df.T
k3df = k3df.join(df['emotion'])     # Join the emotion labels
k3df

f1   f2        f3  emotion
0    0.504098  3.0  0.251466      7.0
1    1.069316  3.0  0.537829      5.0
2    0.504098  3.0  0.251466      7.0
3    1.069316  3.0  0.841627      3.0
4    1.069316  3.0  0.482566      5.0
..        ...  ...       ...      ...
322  0.565217  3.0  0.341627      1.0
323  0.565217  3.0  0.341627      3.0
324  1.069316  3.0  0.537829      3.0
325  2.004098  3.0  2.251466      7.0
326  1.069316  3.0  0.482566      5.0

[327 rows x 4 columns]

In [ ]:
k3df.to_csv('k3means_eye.csv')

**Now we can get to training classifiers on both these sets of new features, and then testing them.**
